version: '3.2'
services:
  db:
    image: postgres
    ports:
      - '5435:5432'
  app:
    build: .
    command: ./scripts/start
    env_file:
      - '.env'
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    links:
      - db
