db:
  image: postgres
  ports:
    - "5435:5432"

app:
  env_file: .env
  build: .
  dockerfile: Dockerfile
  command: ./scripts/start
  volumes_from:
    - gems
    - source_code
  ports:
    - "3000:3000"
  links: &app_links
    - db

gems:
  image: busybox
  volumes:
    - /gems

source_code:
  image: busybox
  volumes:
    - .:/cart-system
