default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cart_system_development

test:
  <<: *default
  database: cart_system_test

production:
  <<: *default
  database: cart_system_production
  password: <%= ENV['CART_SYSTEM_DATABASE_PASSWORD'] %>
