# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9058b423226d1f456897d873a3104f2fc80898169cbf568bf9255bbca2782a461ea641cbc7273501d6d093d6c84a4f4c7e6d30c188f9ed24d4046333b41b000b

test:
  secret_key_base: 43b963bfe313a2078eb1acf35bafae263b985e2ca57658e4a408bdc89de3427e833e6920ad6ff76b63b987afeaf6a6a7869d2edf8588c02a12590398eea7a351

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
