#!/usr/bin/env bash

pid_file=tmp/pids/server.pid

if [ -f "$pid_file" ]; then
  echo "Giving permission to remove old pid"
  chown root:root "$pid_file"
  echo "Removing old pid"
  rm -f "$pid_file"
fi

echo "Starting app server"
bundle exec rails s -p 3000 -b '0.0.0.0'
